steps:
#Running test cases
- name: maven:3-jdk-11
  entrypoint: mvn
  args: ["test"]
#Running **mvn clean install** and skipping test cases
- name: maven:3-jdk-11
  entrypoint: mvn
  args: ["clean", "install", "-Dmaven.test.skip=true"]
#Build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-appengine-demo', '.']
#Push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcp-appengine-demo']
#Deploy image
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', "--image-url=gcr.io/$PROJECT_ID/gcp-appengine-demo"]
  timeout: '1600s'
images:
- gcr.io/$PROJECT_ID/gcp-appengine-demo
